SubsDownloader
==============
Automatically download subtitles for a list of files in an incoming queue
directory, and store both (video and subtitle) in an outgoing one.

This first version will use `opensubtitles.org`_ API.
To get the best subtitle match, this first version will need the video file just
to get a hash from it, later version will work with name lists.

.. _`opensubtitles.org`: http://www.opensubtitles.org

Todo
====
* Keep track of the number of subtitles downloaded per day to fulfill quotas.
* Send emails when subtitles get downloaded.

Contact
=======
Martín Marrese - marrese@gmail.com
